from __future__ import annotations

from typing import Any, Protocol, Sequence


class DashboardPrincipal(Protocol):
    user_id: str
    roles: Sequence[str]
    permissions: Sequence[str]
    workspace_scopes: Sequence[str]
    active_project_id: str | None


class DashboardRepositoryPort(Protocol):
    def get_current_template(self, **query: Any) -> Any: ...
    def get_template_version(self, **query: Any) -> Any: ...
    def list_template_versions(self, **query: Any) -> list[dict[str, Any]]: ...
    def get_preferences(self, **query: Any) -> dict[str, Any] | None: ...
    def save_preferences(self, **command: Any) -> dict[str, Any]: ...
    def delete_preferences(self, **command: Any) -> None: ...
    def create_saved_view(self, **command: Any) -> Any: ...
    def list_saved_views(self, **query: Any) -> list[Any]: ...
    def get_saved_view(self, **query: Any) -> Any: ...
    def delete_saved_view(self, **command: Any) -> None: ...
    def publish_template(self, **command: Any) -> Any: ...
    def create_share(self, **command: Any) -> Any: ...
    def get_share(self, **query: Any) -> Any: ...


class OntologyQueryPort(Protocol):
    def query_objects(self, **query: Any) -> dict[str, Any]: ...
    def traverse(self, **query: Any) -> Any: ...


class EquipmentStatusQueryPort(Protocol):
    def equipment_status(self, equipment_id: str, **scope: Any) -> dict[str, Any]: ...


class DiagnosisReadModelQueryPort(Protocol):
    def diagnosis_read_model(self, **query: Any) -> Sequence[dict[str, Any]]: ...


class MaintenanceQueryPort(Protocol):
    def work_orders(self, **query: Any) -> Sequence[dict[str, Any]]: ...


class DashboardApplicationPort(Protocol):
    """Template use cases exposed to cross-context application orchestrators."""

    def current_template(self, **query: Any) -> Any: ...
    def validate_template_draft(self, **command: Any) -> Any: ...
    def publish_template(self, **command: Any) -> Any: ...


__all__ = [
    "DashboardPrincipal",
    "DashboardApplicationPort",
    "DashboardRepositoryPort",
    "DiagnosisReadModelQueryPort",
    "EquipmentStatusQueryPort",
    "MaintenanceQueryPort",
    "OntologyQueryPort",
]
