"""Typed visualization registry, field profiling and deterministic recommendation."""

from .models import (
    CompiledVisualizationQuery,
    FieldMapping,
    FieldProfile,
    GovernedVisualizationSource,
    OverrideCompatibility,
    SemanticCatalogContext,
    SemanticFieldCatalogEntry,
    SemanticMeasure,
    SemanticOrder,
    SemanticQueryFilter,
    SemanticVisualizationPlanRequest,
    SemanticVisualizationPlanResponse,
    TypedVisualizationQueryPlan,
    VisualizationCandidate,
    VisualizationKind,
    VisualizationRecommendation,
    VisualizationOverride,
)
from .profiler import profile_rows
from .recommender import VISUALIZATION_REGISTRY, recommend_visualization
from .semantic import (
    CATALOG_VERSION,
    DERIVED_EXPRESSION_REGISTRY,
    build_typed_query_plan,
    build_v3_1_semantic_catalog,
    compile_postgresql_query,
    context_from_source,
    semantic_candidates,
    validate_override,
    validate_override_channel_mapping,
    validate_result_profile_compatibility,
)

__all__ = [
    "CATALOG_VERSION",
    "CompiledVisualizationQuery",
    "DERIVED_EXPRESSION_REGISTRY",
    "FieldMapping",
    "FieldProfile",
    "GovernedVisualizationSource",
    "OverrideCompatibility",
    "SemanticCatalogContext",
    "SemanticFieldCatalogEntry",
    "SemanticMeasure",
    "SemanticOrder",
    "SemanticQueryFilter",
    "SemanticVisualizationPlanRequest",
    "SemanticVisualizationPlanResponse",
    "TypedVisualizationQueryPlan",
    "VISUALIZATION_REGISTRY",
    "VisualizationCandidate",
    "VisualizationKind",
    "VisualizationRecommendation",
    "VisualizationOverride",
    "build_typed_query_plan",
    "build_v3_1_semantic_catalog",
    "compile_postgresql_query",
    "context_from_source",
    "profile_rows",
    "recommend_visualization",
    "semantic_candidates",
    "validate_override",
    "validate_override_channel_mapping",
    "validate_result_profile_compatibility",
]
